/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSinaisRouteImport } from './routes/_authenticated/sinais'
import { Route as AuthenticatedEstrategiasRouteImport } from './routes/_authenticated/estrategias'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicRecentRouteImport } from './routes/api/public/recent'
import { Route as ApiPublicCollectRouteImport } from './routes/api/public/collect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSinaisRoute = AuthenticatedSinaisRouteImport.update({
  id: '/_authenticated/sinais',
  path: '/sinais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstrategiasRoute =
  AuthenticatedEstrategiasRouteImport.update({
    id: '/_authenticated/estrategias',
    path: '/estrategias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecentRoute = ApiPublicRecentRouteImport.update({
  id: '/api/public/recent',
  path: '/api/public/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectRoute = ApiPublicCollectRouteImport.update({
  id: '/api/public/collect',
  path: '/api/public/collect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/sinais': typeof AuthenticatedSinaisRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/sinais': typeof AuthenticatedSinaisRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/estrategias': typeof AuthenticatedEstrategiasRoute
  '/_authenticated/sinais': typeof AuthenticatedSinaisRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/estrategias'
    | '/sinais'
    | '/api/public/collect'
    | '/api/public/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/estrategias'
    | '/sinais'
    | '/api/public/collect'
    | '/api/public/recent'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/app'
    | '/_authenticated/estrategias'
    | '/_authenticated/sinais'
    | '/api/public/collect'
    | '/api/public/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedEstrategiasRoute: typeof AuthenticatedEstrategiasRoute
  AuthenticatedSinaisRoute: typeof AuthenticatedSinaisRoute
  ApiPublicCollectRoute: typeof ApiPublicCollectRoute
  ApiPublicRecentRoute: typeof ApiPublicRecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sinais': {
      id: '/_authenticated/sinais'
      path: '/sinais'
      fullPath: '/sinais'
      preLoaderRoute: typeof AuthenticatedSinaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estrategias': {
      id: '/_authenticated/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof AuthenticatedEstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recent': {
      id: '/api/public/recent'
      path: '/api/public/recent'
      fullPath: '/api/public/recent'
      preLoaderRoute: typeof ApiPublicRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collect': {
      id: '/api/public/collect'
      path: '/api/public/collect'
      fullPath: '/api/public/collect'
      preLoaderRoute: typeof ApiPublicCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedEstrategiasRoute: AuthenticatedEstrategiasRoute,
  AuthenticatedSinaisRoute: AuthenticatedSinaisRoute,
  ApiPublicCollectRoute: ApiPublicCollectRoute,
  ApiPublicRecentRoute: ApiPublicRecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
