/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRecentRouteImport } from './routes/api/public/recent'
import { Route as ApiPublicCollectRouteImport } from './routes/api/public/collect'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecentRoute = ApiPublicRecentRouteImport.update({
  id: '/api/public/recent',
  path: '/api/public/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectRoute = ApiPublicCollectRouteImport.update({
  id: '/api/public/collect',
  path: '/api/public/collect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel' | '/api/public/collect' | '/api/public/recent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel' | '/api/public/collect' | '/api/public/recent'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/api/public/collect'
    | '/api/public/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRoute
  ApiPublicCollectRoute: typeof ApiPublicCollectRoute
  ApiPublicRecentRoute: typeof ApiPublicRecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recent': {
      id: '/api/public/recent'
      path: '/api/public/recent'
      fullPath: '/api/public/recent'
      preLoaderRoute: typeof ApiPublicRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collect': {
      id: '/api/public/collect'
      path: '/api/public/collect'
      fullPath: '/api/public/collect'
      preLoaderRoute: typeof ApiPublicCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRoute,
  ApiPublicCollectRoute: ApiPublicCollectRoute,
  ApiPublicRecentRoute: ApiPublicRecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
