/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SinaisRouteImport } from './routes/sinais'
import { Route as EstrategiasRouteImport } from './routes/estrategias'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRecentRouteImport } from './routes/api/public/recent'
import { Route as ApiPublicCollectRouteImport } from './routes/api/public/collect'

const SinaisRoute = SinaisRouteImport.update({
  id: '/sinais',
  path: '/sinais',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiasRoute = EstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecentRoute = ApiPublicRecentRouteImport.update({
  id: '/api/public/recent',
  path: '/api/public/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectRoute = ApiPublicCollectRouteImport.update({
  id: '/api/public/collect',
  path: '/api/public/collect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/estrategias': typeof EstrategiasRoute
  '/sinais': typeof SinaisRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/estrategias': typeof EstrategiasRoute
  '/sinais': typeof SinaisRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/estrategias': typeof EstrategiasRoute
  '/sinais': typeof SinaisRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/estrategias'
    | '/sinais'
    | '/api/public/collect'
    | '/api/public/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/estrategias'
    | '/sinais'
    | '/api/public/collect'
    | '/api/public/recent'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/estrategias'
    | '/sinais'
    | '/api/public/collect'
    | '/api/public/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  EstrategiasRoute: typeof EstrategiasRoute
  SinaisRoute: typeof SinaisRoute
  ApiPublicCollectRoute: typeof ApiPublicCollectRoute
  ApiPublicRecentRoute: typeof ApiPublicRecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sinais': {
      id: '/sinais'
      path: '/sinais'
      fullPath: '/sinais'
      preLoaderRoute: typeof SinaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategias': {
      id: '/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof EstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recent': {
      id: '/api/public/recent'
      path: '/api/public/recent'
      fullPath: '/api/public/recent'
      preLoaderRoute: typeof ApiPublicRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collect': {
      id: '/api/public/collect'
      path: '/api/public/collect'
      fullPath: '/api/public/collect'
      preLoaderRoute: typeof ApiPublicCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  EstrategiasRoute: EstrategiasRoute,
  SinaisRoute: SinaisRoute,
  ApiPublicCollectRoute: ApiPublicCollectRoute,
  ApiPublicRecentRoute: ApiPublicRecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
